# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesap.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 387)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(190, 160, 41, 28))
        self.btn_7.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(240, 160, 41, 28))
        self.btn_8.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(290, 160, 41, 28))
        self.btn_9.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_9.setObjectName("btn_9")
        self.topla = QtWidgets.QPushButton(self.centralwidget)
        self.topla.setGeometry(QtCore.QRect(340, 220, 41, 28))
        self.topla.setStyleSheet("border-radius:10px;\n"
"background-color:green;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.topla.setObjectName("topla")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(240, 190, 41, 28))
        self.btn_5.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_5.setObjectName("btn_5")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(190, 190, 41, 28))
        self.btn_4.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_4.setObjectName("btn_4")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(290, 190, 41, 28))
        self.btn_6.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_6.setObjectName("btn_6")
        self.cikar = QtWidgets.QPushButton(self.centralwidget)
        self.cikar.setGeometry(QtCore.QRect(340, 190, 41, 28))
        self.cikar.setStyleSheet("border-radius:10px;\n"
"background-color:green;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.cikar.setObjectName("cikar")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(240, 220, 41, 28))
        self.btn_2.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_2.setObjectName("btn_2")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(190, 220, 41, 28))
        self.btn_1.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_1.setObjectName("btn_1")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(290, 220, 41, 28))
        self.btn_3.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_3.setObjectName("btn_3")
        self.bol = QtWidgets.QPushButton(self.centralwidget)
        self.bol.setGeometry(QtCore.QRect(340, 130, 41, 28))
        self.bol.setStyleSheet("border-radius:10px;\n"
"background-color:green;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.bol.setObjectName("bol")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(190, 250, 91, 28))
        self.btn_0.setStyleSheet("border-radius:10px;\n"
"background-color:blue;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.btn_0.setObjectName("btn_0")
        self.esit = QtWidgets.QPushButton(self.centralwidget)
        self.esit.setGeometry(QtCore.QRect(340, 250, 41, 28))
        self.esit.setStyleSheet("border-radius:10px;\n"
"background-color:green;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.esit.setObjectName("esit")
        self.carp = QtWidgets.QPushButton(self.centralwidget)
        self.carp.setGeometry(QtCore.QRect(340, 160, 41, 28))
        self.carp.setStyleSheet("border-radius:10px;\n"
"background-color:green;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.carp.setObjectName("carp")
        self.lblDeger = QtWidgets.QLabel(self.centralwidget)
        self.lblDeger.setGeometry(QtCore.QRect(320, 50, 55, 16))
        self.lblDeger.setStyleSheet("border-radius:10px;")
        self.lblDeger.setText("")
        self.lblDeger.setObjectName("lblDeger")
        self.lblDeger_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblDeger_2.setGeometry(QtCore.QRect(320, 70, 55, 16))
        self.lblDeger_2.setStyleSheet("border-radius:10px;")
        self.lblDeger_2.setText("")
        self.lblDeger_2.setObjectName("lblDeger_2")
        self.txt_Ekran = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Ekran.setGeometry(QtCore.QRect(190, 91, 191, 31))
        self.txt_Ekran.setStyleSheet("border-radius:10px;\n"
"font-weight:bold;\n"
"font-size:18px;\n"
"background-color:#c6c6c6;\n"
"padding:3px 10px;")
        self.txt_Ekran.setText("")
        self.txt_Ekran.setObjectName("txt_Ekran")
        self.temizle = QtWidgets.QPushButton(self.centralwidget)
        self.temizle.setGeometry(QtCore.QRect(190, 130, 91, 28))
        self.temizle.setStyleSheet("border-radius:10px;\n"
"background-color:red;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.temizle.setObjectName("temizle")
        self.virgul = QtWidgets.QPushButton(self.centralwidget)
        self.virgul.setGeometry(QtCore.QRect(290, 250, 41, 28))
        self.virgul.setStyleSheet("border-radius:10px;\n"
"background-color:green;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.virgul.setObjectName("virgul")
        self.yuzde = QtWidgets.QPushButton(self.centralwidget)
        self.yuzde.setGeometry(QtCore.QRect(290, 130, 41, 28))
        self.yuzde.setStyleSheet("border-radius:10px;\n"
"background-color:green;\n"
"font-weight:bold;\n"
"font-size:18px;")
        self.yuzde.setObjectName("yuzde")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 20, 251, 20))
        self.label.setStyleSheet("font-weight:bold;\n"
"font-size:17px;\n"
"margin:auto;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.topla.setText(_translate("MainWindow", "+"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.cikar.setText(_translate("MainWindow", "-"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.bol.setText(_translate("MainWindow", "/"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.esit.setText(_translate("MainWindow", "="))
        self.carp.setText(_translate("MainWindow", "X"))
        self.temizle.setText(_translate("MainWindow", "C"))
        self.virgul.setText(_translate("MainWindow", ","))
        self.yuzde.setText(_translate("MainWindow", "%"))
        self.label.setText(_translate("MainWindow", "HESAP MAKİNASI"))
